### ISSUE TITLE
Pull `/utils/BaseStore.js` into it's own module

### ISSUE THREAD

**Issue by jedireza** [yahoo/dispatchr#36]
We should discuss the best way to abstract the `/utils/BaseStore.js` and `/utils/createStore.js` into a separate module.

**Comment by jedireza** [comment]
Maybe it's better to frame this as... Where is the best home for these utils? In general it would be nice to get access to them without depending on `dispatchr`. Maybe they could live in []fluxible/utils/`](https://github.com/yahoo/fluxible/tree/master/utils)?

**Comment by gpbl** [comment]
How should they *not* depend from dispatchr, since they expect a dispatcher with `getContext`? If they are also strictly connected with fluxibile, I'd agree to move them there. A proxy to another package's module looks weird.

It may be useful first check if and how [packages depending on `dispatchr`] (https://www.npmjs.com/browse/depended/dispatchr) are using them.
